### ISSUE TITLE
Spacing between lines and characters

### ISSUE THREAD

**Issue by Void-Spce** [desjarlais/Scintilla.NET#102]
I want to create a space between the lines and between the written characters, how can I do this?

**Comment by desjarlais** [comment]
Try using ExtraAscent and ExtraDescent for the spacing between lines.  

I'm not aware of a way to get extra space between characters.  What is the reason for adding space?

**Comment by Void-Spce** [comment]
thanks

**Comment by desjarlais** [comment]
Reopen if you still need more help with the space between characters, I just need more context for what you are trying to accomplish.
