### ISSUE TITLE
Function segmentation and Accolade

### ISSUE THREAD

**Issue by Void-Spce** [desjarlais/Scintilla.NET#103]
If I want to segment a part of the code between two brackets or a function, is there a Regex or Property that I can set? And is it the same in different lexers?
Also, how can I close automatically when a bracket, parenthesis, brace, tag is written in html and xml?

<img width="86" alt="Untitled" src="https://github.com/desjarlais/Scintilla.NET/assets/154493708/a5c7bb6e-ad46-41d4-b2bd-44dd55e5cb23">

**Comment by desjarlais** [comment]
There are a couple questions here, for the sake of this post, I'll stick to the first, which is "to segment a part of the code between two brackets or a function...?"

Where are you expecting the segmenting to happen, immediately after the first bracket?  Also, what is the intent of the line that essentially the white space after it does not provide?

**Comment by Void-Spce** [comment]
The last question is different, but the first and second questions are also complementary because the **BackEnd** codes are different from the **FrontEnd**, I want this division to be done on the opened accolade because I want the function name, but in Xml or Html on the first tag opened in Wherever this division is done.
**Can I ask the last question in another question?**

**Comment by desjarlais** [comment]
I would add the last question in a separate issue.  

As for the original questions, are you looking for a visible segmentation?  Can you provide repro steps for what you are seeing?

**Comment by Void-Spce** [comment]
<img width="529" alt="Untitled" src="https://github.com/desjarlais/Scintilla.NET/assets/154493708/daa55e48-eed3-4604-b609-a895ca4c04c0">

<img width="546" alt="Untitled2" src="https://github.com/desjarlais/Scintilla.NET/assets/154493708/a65fc883-d9d2-4bb6-8752-b144f76abefd">

<img width="642" alt="Untitled3" src="https://github.com/desjarlais/Scintilla.NET/assets/154493708/62f7dc37-1c89-4ae0-b6fb-0858a1a64002">

<img width="320" alt="Untitled5" src="https://github.com/desjarlais/Scintilla.NET/assets/154493708/93e75f4d-bc4d-4960-9d6a-a7f66aa3eddc">

<img width="270" alt="Untitled6" src="https://github.com/desjarlais/Scintilla.NET/assets/154493708/fbed7e01-05cb-4396-a820-33c14e508b42">

<img width="180" alt="Untitled7" src="https://github.com/desjarlais/Scintilla.NET/assets/154493708/5ed04472-30f9-40d8-9235-cbb15cf26e3d">

The above images are normal and opened in different languages, can this segmentation be done like the Visual Studio environment, or does it put a horizontal line under all the segments?

**Comment by desjarlais** [comment]
What is the code you are using to setup the fold?  I don't repro this issue.

**Comment by Void-Spce** [comment]
```
scintilla.IndentationGuides = IndentView.LookBoth;
scintilla.Styles[Style.BraceLight].BackColor = Color.LightGray;
scintilla.Styles[Style.BraceLight].ForeColor = Color.Black;
scintilla.ExtraAscent = 10;
scintilla.ExtraDescent = 10;
scintilla.TabIndents = true;
scintilla.Margins[0].Width = 50;
scintilla.AutomaticFold = AutomaticFold.Show | AutomaticFold.Click | AutomaticFold.Change;
scintilla.SetFoldFlags(FoldFlags.LineBeforeExpanded);
scintilla.SetFoldMarginHighlightColor(true , Color.CornflowerBlue);
scintilla.FoldDisplayTextSetStyle(FoldDisplayText.Hidden);
```

**I use these settings but there is no fold**

result:
<img width="145" alt="Untitled" src="https://github.com/desjarlais/Scintilla.NET/assets/154493708/a88693b1-4567-448a-a4ba-198ed58f94f2">

**Comment by desjarlais** [comment]
I don't see the horizontal line in your screenshot, I'm confused about what you are trying to accomplish.  I thought you were asking how to remove it?

**Comment by Void-Spce** [comment]
My question is how do I fold the code in Scintilla and can I do this folding custom and make it look like Visual Studio? If you have noticed, in Visual Studio, the codes after folding in the Xml tags are gray and the name of the tag is written, and in the C# code, after the code is folded, a square with 3 dots is placed next to it. code, and the first line of code is written in it.

**Comment by Void-Spce** [comment]
My question is how do I fold the code in Scintilla since there is no code folding square in the settings I made for the library?
Is it possible to customize the appearance of code folding to look like Visual Studio?
If you look carefully, in the 6 images I sent you, you can see how to fold the codes in Visual Studio and Notepad 3. I think the Notepad3 program used your library and the folded code looks primitive. Can I change its appearance?
**For now, I just want the codes to be folded.**

**Comment by desjarlais** [comment]
How close does this get you?

https://gist.github.com/desjarlais/5e819f48c777d0b96a4f7fe2fb739a2e

**Comment by Void-Spce** [comment]
result:
<img width="201" alt="295491424-75048f88-20f6-43d1-8d1b-840b07828dd0" src="https://github.com/desjarlais/Scintilla.NET/assets/154493708/216a9d29-fba0-4fca-913f-7008b1ddc5c3">


This gives the same result. I want there to be + and - signs for nested tags so that I can, for example, by pressing the - sign, a tag will be closed with internal tags, and that sign will change to +, then by pressing the + sign again, all View tags.

What I want is the following and it happens in all Lexers:

![Rec 0001](https://github.com/desjarlais/Scintilla.NET/assets/154493708/1fcfc058-57ec-46e0-a454-212d36f6c94c)

**Comment by desjarlais** [comment]
I'm not sure how you are modifying it, but they are not the same result and it does get you closer from what I can tell.  If you literally copy and paste from the link I sent, you should get this:

![image](https://github.com/desjarlais/Scintilla.NET/assets/9721728/5bf0886c-a27f-460e-900e-9be2c9dfd6e0)

This will get you the + and -, look at the comment "// Style the folder markers" and you likely only need to add the ascent from your earlier question.

So the only thing missing is showing the end tag with the start tag in an enclosed textbox when collapsed, correct?

**Comment by Void-Spce** [comment]
I use your code with some changes in the settings in this way, is there a problem with these settings, it means that these settings must be done in the form of the code you wrote:

```
scintilla.StyleResetDefault();
scintilla.Styles[Style.Default].Size = 12;
scintilla.IndentationGuides = IndentView.LookBoth;
scintilla.Styles[Style.BraceLight].BackColor = Color.LightGray;
scintilla.Styles[Style.BraceLight].ForeColor = Color.Black;
scintilla.ExtraAscent = 10;
scintilla.ExtraDescent = 10;
scintilla.TabIndents = true;
            
scintilla.SetProperty("fold", "1");
scintilla.SetProperty("fold.compact", "1");
scintilla.SetProperty("fold.html", "1");
scintilla.Margins[0].Width = 100;
scintilla.Margins[1].Width = 20;
scintilla.Margins[2].Width = 30;
scintilla.Margins[2].Type = MarginType.Symbol;
scintilla.Margins[2].Mask = Marker.MaskFolders;
scintilla.Margins[2].Sensitive = true;
            
for (int i = Marker.FolderEnd; i <= Marker.FolderOpen; i++)
{
       scintilla.Markers[i].SetForeColor(SystemColors.ControlLightLight);
       scintilla.Markers[i].SetBackColor(SystemColors.ControlDark);
}

scintilla.Markers[Marker.Folder].Symbol = MarkerSymbol.BoxPlus;
scintilla.Markers[Marker.Folder].SetBackColor(SystemColors.ControlText);
scintilla.Markers[Marker.FolderOpen].Symbol = MarkerSymbol.BoxMinus;
scintilla.Markers[Marker.FolderEnd].Symbol = MarkerSymbol.BoxPlusConnected;
scintilla.Markers[Marker.FolderEnd].SetBackColor(SystemColors.ControlText);
scintilla.Markers[Marker.FolderMidTail].Symbol = MarkerSymbol.TCorner;
scintilla.Markers[Marker.FolderOpenMid].Symbol = MarkerSymbol.BoxMinusConnected;
scintilla.Markers[Marker.FolderSub].Symbol = MarkerSymbol.VLine;
scintilla.Markers[Marker.FolderTail].Symbol = MarkerSymbol.LCorner;

scintilla.AutomaticFold = AutomaticFold.Show | AutomaticFold.Click | AutomaticFold.Change;

switch (extFile.Replace(".", "").ToLower())
{
          case "xml":
                    scintilla.LexerName = "xml";

                    scintilla.Styles[Style.Xml.Tag].ForeColor = Color.LightCoral;
                    scintilla.Styles[Style.Xml.Comment].ForeColor = Color.DarkCyan;
                    scintilla.Styles[Style.Xml.Attribute].ForeColor = Color.RoyalBlue;
                    scintilla.Styles[Style.Xml.Entity].ForeColor = Color.RoyalBlue;
                    scintilla.Styles[Style.Xml.DoubleString].ForeColor = Color.Gray;
                    scintilla.Styles[Style.Xml.SingleString].ForeColor = Color.Gray;
               break;
}```

**Comment by desjarlais** [comment]
Is that closer to what you are looking for, with the only difference being the collapsed textbox showing "Start Tag ... End Tag"?

**Comment by Void-Spce** [comment]
I have even put 
```
scintilla.Styles[Style.Xml.XmlStart].ForeColor = Color.Blue;
scintilla.Styles[Style.Xml.TagEnd].ForeColor = Color.Blue;
```
but the + and - signs are still not added. I am using Scintilla.NET version 5.3.2.9 in .net core 7 Is it possible that the problem is with the library version?

**Comment by desjarlais** [comment]
Possibly, use the Scintilla5.NET package from nuget, which should be up to date.

**Comment by Void-Spce** [comment]
```
scintilla.StyleResetDefault();scintilla.Styles[Style.Default].Size=12;
scintilla.IndentationGuides=IndentView.LookBoth;
scintilla.Styles[Style.BraceLight].BackColor=Color.LightGray;
scintilla.Styles[Style.BraceLight].ForeColor=Color.Black;
scintilla.ExtraAscent=10;
scintilla.ExtraDescent=10;
scintilla.TabIndents=true;
scintilla.SetProperty("fold","1");
scintilla.SetProperty("fold.compact","1");
scintilla.SetProperty("fold.html","1");
scintilla.Margins[0].Width=100;
scintilla.Margins[1].Width=20;
scintilla.Margins[2].Width=30;
scintilla.Margins[2].Type=MarginType.Symbol;
scintilla.Margins[2].Mask=Marker.MaskFolders;
scintilla.Margins[2].Sensitive=true;

for(inti=Marker.FolderEnd;i<=Marker.FolderOpen;i++)
{
    scintilla.Markers[i].SetForeColor(SystemColors.ControlLightLight);
    scintilla.Markers[i].SetBackColor(SystemColors.ControlDark);
}

scintilla.Markers[Marker.Folder].Symbol=MarkerSymbol.BoxPlus;
scintilla.Markers[Marker.Folder].SetBackColor(SystemColors.ControlText);
scintilla.Markers[Marker.FolderOpen].Symbol=MarkerSymbol.BoxMinus;
scintilla.Markers[Marker.FolderEnd].Symbol=MarkerSymbol.BoxPlusConnected;
scintilla.Markers[Marker.FolderEnd].SetBackColor(SystemColors.ControlText);
scintilla.Markers[Marker.FolderMidTail].Symbol=MarkerSymbol.TCorner;
scintilla.Markers[Marker.FolderOpenMid].Symbol=MarkerSymbol.BoxMinusConnected;
scintilla.Markers[Marker.FolderSub].Symbol=MarkerSymbol.VLine;
scintilla.Markers[Marker.FolderTail].Symbol=MarkerSymbol.LCorner;

scintilla.AutomaticFold=AutomaticFold.Show|AutomaticFold.Click|AutomaticFold.Change;

switch(extFile.Replace(".","").ToLower())
{
    case"xml":
      scintilla.LexerName="xml";
      scintilla.Lexer=Lexer.Xml;
      scintilla.Styles[Style.Xml.Tag].ForeColor=Color.LightCoral;
      scintilla.Styles[Style.Xml.Comment].ForeColor=Color.DarkCyan;
      scintilla.Styles[Style.Xml.Attribute].ForeColor=Color.RoyalBlue;
      scintilla.Styles[Style.Xml.Entity].ForeColor=Color.RoyalBlue;
      scintilla.Styles[Style.Xml.DoubleString].ForeColor=Color.Gray;
      scintilla.Styles[Style.Xml.SingleString].ForeColor=Color.Gray;
      scintilla.Styles[Style.Xml.XmlStart].ForeColor=Color.Blue;
      scintilla.Styles[Style.Xml.TagEnd].ForeColor=Color.Blue;
}
```
result:
<img width="423" alt="Untitled" src="https://github.com/desjarlais/Scintilla.NET/assets/154493708/093e7909-1726-48da-a3d5-46a0a5938445">
library:
<img width="286" alt="Untitled2" src="https://github.com/desjarlais/Scintilla.NET/assets/154493708/a6e5cc49-d5b1-4887-97e7-9fd81aa7b4fb">

**Comment by desjarlais** [comment]
The runtime isn't the problem, when you set the following appears to be the problem:

scintilla.LexerName = "xml";

move that call to the beginning of your code to set the style/props:

scintilla.LexerName="xml";
scintilla.StyleResetDefault();
scintilla.Styles[Style.Default].Size=12;
scintilla.IndentationGuides=IndentView.LookBoth;
scintilla.Styles[Style.BraceLight].BackColor=Color.LightGray;
scintilla.Styles[Style.BraceLight].ForeColor=Color.Black;
scintilla.ExtraAscent=10;
scintilla.ExtraDescent=10;
scintilla.TabIndents=true;
scintilla.SetProperty("fold","1");
scintilla.SetProperty("fold.compact","1");
scintilla.SetProperty("fold.html","1");
scintilla.Margins[0].Width=100;
scintilla.Margins[1].Width=20;
scintilla.Margins[2].Width=30;
scintilla.Margins[2].Type=MarginType.Symbol;
scintilla.Margins[2].Mask=Marker.MaskFolders;
scintilla.Margins[2].Sensitive=true;

for(inti=Marker.FolderEnd;i<=Marker.FolderOpen;i++)
{
    scintilla.Markers[i].SetForeColor(SystemColors.ControlLightLight);
    scintilla.Markers[i].SetBackColor(SystemColors.ControlDark);
}

scintilla.Markers[Marker.Folder].Symbol=MarkerSymbol.BoxPlus;
scintilla.Markers[Marker.Folder].SetBackColor(SystemColors.ControlText);
scintilla.Markers[Marker.FolderOpen].Symbol=MarkerSymbol.BoxMinus;
scintilla.Markers[Marker.FolderEnd].Symbol=MarkerSymbol.BoxPlusConnected;
scintilla.Markers[Marker.FolderEnd].SetBackColor(SystemColors.ControlText);
scintilla.Markers[Marker.FolderMidTail].Symbol=MarkerSymbol.TCorner;
scintilla.Markers[Marker.FolderOpenMid].Symbol=MarkerSymbol.BoxMinusConnected;
scintilla.Markers[Marker.FolderSub].Symbol=MarkerSymbol.VLine;
scintilla.Markers[Marker.FolderTail].Symbol=MarkerSymbol.LCorner;

scintilla.AutomaticFold=AutomaticFold.Show|AutomaticFold.Click|AutomaticFold.Change;

switch(extFile.Replace(".","").ToLower())
{
    case"xml":
      scintilla.Styles[Style.Xml.Tag].ForeColor=Color.LightCoral;
      scintilla.Styles[Style.Xml.Comment].ForeColor=Color.DarkCyan;
      scintilla.Styles[Style.Xml.Attribute].ForeColor=Color.RoyalBlue;
      scintilla.Styles[Style.Xml.Entity].ForeColor=Color.RoyalBlue;
      scintilla.Styles[Style.Xml.DoubleString].ForeColor=Color.Gray;
      scintilla.Styles[Style.Xml.SingleString].ForeColor=Color.Gray;
      scintilla.Styles[Style.Xml.XmlStart].ForeColor=Color.Blue;
      scintilla.Styles[Style.Xml.TagEnd].ForeColor=Color.Blue;
   break;
}

**Comment by Void-Spce** [comment]
Thank you
What should be done just to make the size + and - smaller, because it is big?

Can the folding be customized, that is, it can be done in Visual Studio.

<img width="286" alt="Untitled" src="https://github.com/desjarlais/Scintilla.NET/assets/154493708/c86b65f0-c4aa-4bbf-9526-f76ee94a52e5">

**Comment by desjarlais** [comment]
Try a smaller margin 2 width:

scintilla.Margins[2].Width=15;
