### ISSUE TITLE
SetLexerByName does not cache the lexer created, instead it creates a new one each time.

### ISSUE THREAD

**Issue by Pabs84** [desjarlais/Scintilla.NET#104]
**Describe the bug**
SetLexerByName does not cache the lexer created, instead it creates a new one each time. 

**To Reproduce**
call SetLexerByName(valid_lexer_name) multiple times, each time a new handle is created

**Expected behavior**
call SetLexerByName(valid_lexer_name) multiple times, only the first time a new handle is created, this avoid a memory leakage in lexilla

a Dictionary<string, IntPtr>lexerName to Handle might be necessary.

this behavior is particularly important for applications dynamically selecting the lexer

**Comment by desjarlais** [comment]
Thank you for the report, I think you are right, each new lexer might need to be added to a dictionary and re-used.

**Comment by Pabs84** [comment]
I tried it and it gives me issues. 😅😓 access violation

**Comment by desjarlais** [comment]
How are you reproducing the issue?  Do you have a code sample?

**Comment by desjarlais** [comment]
@Pabs84 I'm not seeing any leaks yet, can you provide a sample of what you are doing to see the extra handle?

**Comment by Pabs84** [comment]
wpf xaml
```
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        xmlns:ScintillaNET="clr-namespace:ScintillaNET;assembly=Scintilla.NET"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <WindowsFormsHost>
            <ScintillaNET:Scintilla x:Name="Text" Margin="10,31,10,10">
            </ScintillaNET:Scintilla>
        </WindowsFormsHost>
    </Grid>
</Window>
```

c++
```
using System.Windows;
using static ScintillaNET.Style;
using static System.Drawing.Color;

namespace WpfApp1
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            Text.StyleResetDefault();
            Text.Styles[Default].Font = "Consolas";
            Text.Styles[Default].Size = 10;
            Text.Styles[Default].ForeColor = Black;
            Text.StyleClearAll();

            Text.LexerName = "json";
            Text.Styles[Json.Default].ForeColor = Silver;
            Text.Styles[Json.BlockComment].ForeColor = Green;
            Text.Styles[Json.LineComment].ForeColor = Green;
            Text.Styles[Json.Number].ForeColor = Olive;
            Text.Styles[Json.PropertyName].ForeColor = Blue;
            Text.Styles[Json.String].ForeColor = Brown;
            Text.Styles[Json.StringEol].BackColor = Pink;
            Text.Styles[Json.Operator].ForeColor = Purple;
            Text.Styles[Json.Error].ForeColor = Red;
            Text.Styles[Json.Keyword].ForeColor = Orange;
            Text.SetKeywords(0, "false true null");

            int start;
            Text.LexerName = "json";
            start = Text.TextLength;
            Text.AppendText("{\"hello\":\"world\"}\r\n");
            Text.Colorize(start, Text.TextLength);
            Text.LexerName = "null";
            start = Text.TextLength;
            Text.AppendText("just normal text\r\n");
            Text.Colorize(start, Text.TextLength);
        }
    }
}
```
this code seems to work just fine, it uses legitimate sequence and it looks trivial. so I believe is a good example.

If I add a dictionary I break everything, and so it seems **scintilla retains the lexer not as a descriptor but as a live object**:
Scintilla.cs line 198
```
        private static Dictionary<string, IntPtr> lexerDictionary = new();
        /// <summary>
        /// Sets the name of the lexer by its name.
        /// </summary>
        /// <param name="lexerName">Name of the lexer.</param>
        /// <returns><c>true</c> if the lexer was successfully set, <c>false</c> otherwise.</returns>
        private bool SetLexerByName(string lexerName)
        {
			// this special case is reserved to select the container to do the styling, in which case the container is sent a StyleNeeded notification each time text needs styling for display.
            if (lexerName == String.Empty)
            {
                DirectMessage(NativeMethods.SCI_SETILEXER, IntPtr.Zero, IntPtr.Zero);
                return true;
            }
            IntPtr ptr = IntPtr.Zero;
            if (!lexerDictionary.TryGetValue(lexerName, out ptr))
            {
                ptr = Lexilla.CreateLexer(lexerName);

                if (ptr == IntPtr.Zero)
                {
                    return false;
                }

                lexerDictionary.Add(lexerName, ptr);
            }

            DirectMessage(NativeMethods.SCI_SETILEXER, IntPtr.Zero, ptr);

            return true;
        }
```

after you apply this patch you will see it is either not working as expected or 9 times out of 10 will crash with `System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`

So, my conclusion is, if scintilla is retaining the lexer as a live object (rather then a descriptor) the ownership is implicitly transferred to scintilla and this seems the case. this is because only scintilla internals have enough knowledge to determine when a live object can be successfully terminated; by extension the user API can only feed new object, any other manipulation would be hard. this is why the api is trivially just createLexer() from lexilla.dll and transfer using SCI_SETILEXER to scintilla.dll.
the harvesting of the lexer would be for example the user selects the whole doc and press 'delete' button, at this point scintilla handles the text update and can safely collect all lexers now not referenced anymore. the user app is not involved. so my conclusion is that even if we could prove there is a memory leakage, it lands entirely on scintilla/lexilla internals, not this wrapper. I propose to 'close the issue as not planned'. some brief info in the documentation would not be bad though.

the documentation should just mention: lexilla.dll createLexer output is not a descriptor that can be reused, but rather a live object and as such once using SCI_SETILEXER we cannot reference it locally any longer.

**Comment by desjarlais** [comment]
That does repro, I'll try to debug and see what I can find out.  You are probably right about what is going on, but I'm going to take a look.

**Comment by desjarlais** [comment]
I think you are correct, the underlying object for the lexer goes away so having the .net ptr to it and cached isn't going to work.  Closing as wont fix.
