### ISSUE TITLE
Implement SCI_[G|S]ETCHANGEHISTORY

### ISSUE THREAD

**Issue by dpmm99** [desjarlais/Scintilla.NET#105]
If I'm not mistaken, the two "change history" methods have yet to be implemented: https://www.scintilla.org/ScintillaDoc.html#SCI_SETCHANGEHISTORY

**Comment by desjarlais** [comment]
I don't see changehistory in the project, give me a few days to look into what it would take to add it in.

**Comment by desjarlais** [comment]
still investigating this one.
