### ISSUE TITLE
Text does not style completely unless scrolled

### ISSUE THREAD

**Issue by Aghlara** [desjarlais/Scintilla.NET#107]
When we have a textbox with custom styling. The style does not get applied completely even though it is visible. (look at lines 26 onward)
![image](https://github.com/desjarlais/Scintilla.NET/assets/5187409/f0d5d285-850b-46d8-bc69-c0e6b8db2e75)

I like to render the full text once it is visible, not the parts that are hidden. 

Any idea how to achieve this?

**Comment by desjarlais** [comment]
I think the information you are looking for is here:

https://github.com/desjarlais/Scintilla.NET/wiki/Custom-Syntax-Highlighting

**Comment by Aghlara** [comment]
Unfortunately not. my question is not how to write a custom style or parser. As you see in the image that part it is working fine. The issue is it highlights as I scroll or focus. I want the document style as I scroll without clicking and focusing.

![nl-render](https://github.com/desjarlais/Scintilla.NET/assets/5187409/116199ca-712f-4791-b01c-4f2eb0f2f9f8)

**Comment by desjarlais** [comment]
I'll try to work on creating a sample to test, but doesn't the second section of the article discuss the scrolling aspect?

https://github.com/desjarlais/Scintilla.NET/wiki/Custom-Syntax-Highlighting#handling-the-styleneeded-event

**Comment by Aghlara** [comment]
I'll recheck it again. Thanks for pointing that out.

**Comment by Aghlara** [comment]
OK I tested it. By doing `Style(Editor, Editor.GetEndStyled(), e.Position)` that's the behaviour you see on the image.

My question is now, if there is a way to do it on more quicker basis, rather than a 2(ish) second delay?

**Comment by desjarlais** [comment]
Just to make sure I'm understanding you, the scrolling is working as expected now but you see a 2 second delay?

**Comment by desjarlais** [comment]
The only suggestion I would have is to kick off a background thread to re-style the remaining text after the currently visible text is finished.  Closing for now, but if you need more information, re-open and we can discuss it further.
