### ISSUE TITLE
Applying styles dynamically and loading from a settings file issue 

### ISSUE THREAD

**Issue by PyronoxO** [desjarlais/Scintilla.NET#110]
Hello everyone, i have a small issue that is driving me crazy, i setup my styles  like the example below  now when i run the app and load a file everything shows ok  an i intentionally want the  editor font and the line number  font to be different now  when i change the font from a font dialog and save the value to a settings file  i call for those 2  voids to update the fonts of the editor  now what happens is both line numbers and  editor  font change together.  so my question is does  scintilla1.Styles[Style.Default].Font overwrite  the line numbers  font  and why ?

how things are supposed to be  when i first load the app  ( excuse the crazy fonts, just to showcase the difference )

![image](https://github.com/desjarlais/Scintilla.NET/assets/92161574/f98465dc-0332-420c-9237-7a6b84930dd3)

Here is how it becomes after changing the font 

![image](https://github.com/desjarlais/Scintilla.NET/assets/92161574/fef7c185-f0ef-42f9-8689-df197a103afa)

public void jsonStyling()

{
    // scintilla1.StyleClearAll();

    // Configure thejson style

    scintilla1.StyleResetDefault();
    string? tt = Properties.Settings1.Default.DeFont.OriginalFontName;
    scintilla1.Styles[Style.Default].Font = tt;
    scintilla1.Styles[Style.Default].SizeF = Properties.Settings1.Default.DeFont.Size;
    scintilla1.Styles[Style.Default].Italic = Properties.Settings1.Default.DeFont.Italic;
    scintilla1.Styles[Style.Default].Bold = Properties.Settings1.Default.DeFont.Bold;
    scintilla1.Styles[Style.Default].ForeColor = Properties.Settings1.Default.Dforecolor;
    scintilla1.Styles[Style.Default].BackColor = Properties.Settings1.Default.EditorBC;
    cintilla1.StyleClearAll();
    scintilla1.LexerName = "json";
    scintilla1.SetKeywords(0, "false true");
    scintilla1.SetProperty("lexer.json.allow.comments", "1");
    scintilla1.SetProperty("lexer.json.escape.sequence", "1");
    scintilla1.Styles[Style.Json.Default].ForeColor = Color.Turquoise;
    scintilla1.Styles[Style.Json.LineComment].ForeColor = Color.FromArgb(0, 128, 0); // Green
    scintilla1.Styles[Style.Json.Number].ForeColor = Color.OrangeRed;
    scintilla1.Styles[Style.Json.String].ForeColor = Color.LightSkyBlue;
    scintilla1.Styles[Style.Json.EscapeSequence].ForeColor = Color.LightBlue;
    //Brackets colors
    scintilla1.Styles[Style.Json.Operator].ForeColor = Color.Yellow;
    scintilla1.Styles[Style.Json.Operator].Bold = true;
    //property name
    scintilla1.Styles[Style.Json.PropertyName].ForeColor = Color.AliceBlue;//LightBlue;
    scintilla1.Styles[Style.Json.PropertyName].Italic = true;
    //Keywords
    scintilla1.Styles[Style.Json.Keyword].ForeColor = Color.Green;
    //Errors
    scintilla1.Styles[Style.Json.Error].ForeColor = Color.Red;
    //Braces colors
    scintilla1.Styles[Style.BraceLight].ForeColor = Color.Orange;
    scintilla1.Styles[Style.BraceBad].ForeColor = Color.Red;
    // Set the keywords
}

and 

public void UiStyling()
{
    scintilla1.CaretStyle = ScintillaNET.CaretStyle.Line;

    string caretStyleValue = Properties.Settings1.Default.CaretStyle; // Get the value from the settings

    switch (caretStyleValue)
    {
        case "Line":
            scintilla1.CaretStyle = ScintillaNET.CaretStyle.Line;
            break;

        case "Block":
            scintilla1.CaretStyle = ScintillaNET.CaretStyle.Block;
            break;

        case "Invisible":
            scintilla1.CaretStyle = ScintillaNET.CaretStyle.Invisible;
            break;

        default:
            scintilla1.CaretStyle = ScintillaNET.CaretStyle.Line; // Handle the case where the value is none of the expected options
            break;
    }

    scintilla1.Margins[1].BackColor = Properties.Settings1.Default.MarginBackcolor;
    scintilla1.Margins[0].Type = MarginType.Number;
    scintilla1.Margins[0].BackColor = Properties.Settings1.Default.MarginBackcolor;
    scintilla1.Styles[Style.LineNumber].BackColor = Properties.Settings1.Default.uLineNumBc; //Color.FromArgb(12, 12, 12);
    scintilla1.Styles[Style.LineNumber].ForeColor = Properties.Settings1.Default.uLineNumFc; //Color.Red;
    scintilla1.Styles[Style.LineNumber].Font = "Algerian";    //Properties.Settings1.Default.DeFont.OriginalFontName;
    scintilla1.Styles[Style.LineNumber].SizeF = 16;
    scintilla1.Styles[Style.IndentGuide].ForeColor = Color.Aquamarine;
}

**Comment by desjarlais** [comment]
Not that I'm aware of, I tried a simple test of setting a font for line numbers and then changing the default style font to something else, I don't see it overwrite the line number font.  Can you provide a sample app repro?

**Comment by PyronoxO** [comment]
@desjarlais  here is the repo 

https://github.com/PyronoxO/Json-Editor

**Comment by desjarlais** [comment]
I can't see your repo, is it private?

**Comment by PyronoxO** [comment]
> I can't see your repo, is it private?

it was but i set it to public can you try again ?

**Comment by desjarlais** [comment]
That worked, I'll take a look and reply back.

**Comment by PyronoxO** [comment]
> That worked, I'll take a look and reply back.

Thank you for taking the time, Much appreciated.

**Comment by desjarlais** [comment]
Where is the "Enhanced_Tab_Control" dependency?

![image](https://github.com/desjarlais/Scintilla.NET/assets/9721728/072e164b-16b9-441c-aa4a-fb1833677144)

**Comment by PyronoxO** [comment]
oh its a small user control i made for the tabcontrol to have a close button

**Comment by PyronoxO** [comment]
@desjarlais Hey bro, any  update on the issue ?

**Comment by desjarlais** [comment]
Is there a way to get me the control, otherwise it might take time to pull out how that works in your app and get a functioning repro without it?

**Comment by PyronoxO** [comment]
you dont need it just use a regular tab control it will work

**Comment by PyronoxO** [comment]
@desjarlais  did it work ??

**Comment by desjarlais** [comment]
It did, thank you for including it.

**Comment by PyronoxO** [comment]
> It did, thank you for including it.

no problem, please let me know once you find  the problem

**Comment by PyronoxO** [comment]
@desjarlais  hey bro , any update on the issue ?

**Comment by desjarlais** [comment]
not yet, still working on the repro.  To save time in digging through your project, can you give me the step by step what to do to see the issue reproduce?

**Comment by desjarlais** [comment]
@PyronoxO I do see the line number backcolor change, it happens when you call "scintilla1.StyleClearAll" in "jsonStyling".  

I don't see that the editor font changes, that starts as "Helvetica" and continues through "UiStyling" and "jsonStyling".

For the LineNumber, I think you have to reset that style back after you call "StyleClearAll".  So if you do something like this in "jsonStyling":

scintilla1.StyleClearAll();
scintilla1.Styles[Style.LineNumber].BackColor = Properties.Settings1.Default.uLineNumBc; //Color.FromArgb(12, 12, 12);
scintilla1.Styles[Style.LineNumber].ForeColor = Properties.Settings1.Default.uLineNumFc; //Color.Red;

I think you will see it possibly staying with what you expect?

**Comment by PyronoxO** [comment]
Ill try it and let you know, sorry for thekate reply ill try reproduce the issue again for you

From: Brandon Desjarlais ***@***.***>
Date: Sunday, 17 March 2024 at 8:59 AM
To: desjarlais/Scintilla.NET ***@***.***>
Cc: PyronoxO ***@***.***>, Mention ***@***.***>
Subject: Re: [desjarlais/Scintilla.NET] Applying styles dynamically and loading from a settings file issue (Issue #110)

@PyronoxO<https://github.com/PyronoxO> I do see the line number backcolor change, it happens when you call "scintilla1.StyleClearAll" in "jsonStyling".

I don't see that the editor font changes, that starts as "Helvetica" and continues through "UiStyling" and "jsonStyling".

For the LineNumber, I think you have to reset that style back after you call "StyleClearAll". So if you do something like this in "jsonStyling":

scintilla1.StyleClearAll();
scintilla1.Styles[Style.LineNumber].BackColor = Properties.Settings1.Default.uLineNumBc; //Color.FromArgb(12, 12, 12);
scintilla1.Styles[Style.LineNumber].ForeColor = Properties.Settings1.Default.uLineNumFc; //Color.Red;

I think you will see it possibly staying with what you expect?

**Comment by desjarlais** [comment]
Closing the issue for now, but if that does not work or you need more information, please re-open.
