### ISSUE TITLE
All fields been impacted by setting margin of line number.

### ISSUE THREAD

**Issue by whyy0** [desjarlais/Scintilla.NET#112]
**Describe the bug**

**To Reproduce**
when I set the line number margin as scintilla.Margins[0].Width= 20; 
the cursor start position of **all the text fields** in the form move to 20 px from the left

**Expected behavior**
scintilla configuration should not impact to other components.

**Screenshots**
<img width="290" alt="image" src="https://github.com/desjarlais/Scintilla.NET/assets/20245770/42d112c6-c1fb-47e2-819b-194956aa4dac">

**Desktop (please complete the following information):**
 - OS: windows
 - Version 11

**Additional context**
hope you can help to resolve this issue.

**Comment by whyy0** [comment]
resolved

**Comment by desjarlais** [comment]
Should this be closed or you still need help?

**Comment by desjarlais** [comment]
If you still need help, reopen or create a new issue.
