### ISSUE TITLE
Restore support for .NET Framework 4.6.2

### ISSUE THREAD

**Issue by jj39** [desjarlais/Scintilla.NET#128]
The earliest version of .NET Framework that is still supported is 4.6.2 (end of life is Jan 12, 2027) and ScintillaNET used to have support for 4.6.2 but it seems that 4.6.2 support was removed in favour of 4.7 to use System.ValueTuple: https://github.com/desjarlais/Scintilla.NET/commit/3b4e9756250989eaba61e6b720b9d87585e92408

Please restore support for 4.6.2 by using the System.ValueTuple NuGet package (instead of the built-in System.ValueTuple in .NET Framework 4.7): https://www.nuget.org/packages/System.ValueTuple

**Comment by ahmetsait** [comment]
@jj39 is there actually a hard requirement for your real world project? [Windows 10 Creators Update (Version 1703)](https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-47) includes .NET 4.7 as an OS component.

**Comment by jj39** [comment]
I have a commercial app and use the lowest version of .NET Framework possible to ensure maximum compatibility with all potential users. As you mentioned 4.7 requires a minimum version of Windows 10 and does not support some older versions of Windows 10. While I don’t personally use an older version, many people do and requiring 4.7 would mean that my app would be not be able to be used on the computers of people with older versions of Windows 10.

**Comment by desjarlais** [comment]
@ahmetsait How much are we currently using Tuple's and what is your take on bringing back 462?  I don't remember seeing any Tuple's but it's been a while since I've reviewed those changes after moving to 4.7.

**Comment by ahmetsait** [comment]
Tuple usage is pretty minimal and can be replaced with [System.Tuple](https://learn.microsoft.com/en-us/dotnet/api/system.tuple) if you don't want to introduce another NuGet dependency. @desjarlais I don't know when will I have the time so I would encourage you to tackle this if you do.
