### ISSUE TITLE
NuGet Release v5.5.2 did not properly update .NET Framework dependency to 4.6.2 from 4.7

### ISSUE THREAD

**Issue by jj39** [desjarlais/Scintilla.NET#132]
NuGet Release v5.5.2 did not properly update .NET Framework dependency to 4.6.2 from 4.7 as per https://github.com/desjarlais/Scintilla.NET/issues/128

https://www.nuget.org/packages/Scintilla5.NET#dependencies-body-tab

![2024_07_13_19_52_54_NuGet_Gallery_Scintilla5 NET_5 5 2](https://github.com/user-attachments/assets/c6ecd5a6-6633-48d4-9280-6bf337e07c09)

**Comment by ahmetsait** [comment]
@desjarlais looks like 38d227d accidentally reverts changes to target framework. Also 5.6.0 would be a more appropriate [semver](https://semver.org/) for a release that adds a new feature.

**Comment by desjarlais** [comment]
Good catch @ahmetsait, pushing 5.6.0 today to fix these issues.  Thanks again for the help!
