### ISSUE TITLE
Horizontal scrolling with mouse is backwards

### ISSUE THREAD

**Issue by DustinLuck** [desjarlais/Scintilla.NET#140]
**Describe the bug**
When using a touchpad or mouse with horizontal scrolling, the scintilla editor window scrolls the opposite way of what is expected. In this case, expected refers to the behavior of the vast majority of Windows applications that support horizontal scrolling. The behavior is as expected when using Shift + Scroll Up/Down.

**To Reproduce**
Use the touchpad or scroll wheel to scroll left; the scintilla window scrolls right (and vice versa).

**Expected behavior**
When using the touchpad or scroll wheel to scroll left; the scintilla window scrolls left (and vice versa).

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
 - Windows Forms project
 - .NET Framework 4.8
 - Visual Studio Professional 2022

**Comment by DustinLuck** [comment]
> how are you using the scroll wheel to move left?
Some manufacturers have a built-in horizontal scroll via a dedicated second scroll wheel or rocking the vertical scroll wheel left or right.

> can you test with [SciTE](https://sourceforge.net/projects/scintilla/files/SciTE/5.5.2/)
the same behavior happens with SciTE

**Comment by desjarlais** [comment]
If this reproduces with SciTE, then this wrapper is likely not the cause of the issue...we would need to submit this bug to the native scintilla dll or check if this is a known issue [here](https://sourceforge.net/p/scintilla/bugs/).  I'm guessing this is not implemented yet.

**Comment by desjarlais** [comment]
@DustinLuck would you be able to submit the bug to the native scintilla bug database?  I don't have the mouse/driver that is reproducing this behavior so it might be tricky for me to submit it without a repro.

**Comment by ahmetsait** [comment]
@DustinLuck Seems to be an issue with your own setup. I'm observing correct behavior on my touchpad with both regular and natural/inverse scroll settings.

**Comment by DustinLuck** [comment]
> @DustinLuck Seems to be an issue with your own setup. I'm observing correct behavior on my touchpad with both regular and natural/inverse scroll settings.

Not sure how my setup would affect just one component but I'm going to look into creating a bug report with the Scintilla project.

**Comment by DustinLuck** [comment]
The bug report has been created: https://sourceforge.net/p/scintilla/bugs/2449/
