### ISSUE TITLE
Facing issue while locating the satellite dll's for the basepath

### ISSUE THREAD

**Issue by KalyaniURS** [desjarlais/Scintilla.NET#141]
**Describe the bug**
According to the ScintillaNET.csproj source code, when installing the NuGet package and using the DLL in our solution, it attempts to locate the satellite DLLs in a basepath (e.g., C:\packages\Scintilla.v5.3.3.18\build\x64). However, since our project is located on a different folder, this causes an issue while searching for the satellite dll’s. We need a solution that can dynamically identify the satellite DLLs based on the actual location of the NuGet package, instead of relying on a fixed path.
**To Reproduce**
Either via code or using the Scintilla.NET control.
 If the native dll's are not located in the particular folder i.e C://packages then when we are trying to use the scintilla.dll in our project it will search only in the C://packages path, which causes an issue.

**Expected behavior**
Expectation is that the assemblies should get identified irrespective of the location
**Screenshots**
![image](https://github.com/user-attachments/assets/2f8cd582-3b6a-4fd3-8034-ffa2df987a64)

**Desktop (please complete the following information):**
- OS: [e.g. Windows Server 2022]
- Version [e.g. 21H2]

**Additional context**

**Comment by ahmetsait** [comment]
@KalyaniURS Use the latest ScintillaNET version via [`<PackageReference>`](https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference). Reopen the issue if you're still having issues.
