### ISSUE TITLE
Requesting to include the strong naming for the Scintilla5.Net assembly

### ISSUE THREAD

**Issue by KalyaniURS** [desjarlais/Scintilla.NET#142]
**Is your feature request related to a problem? Please describe.**
After referencing the Scintilla.NET NuGet package (v5.6.1/v5.6.0) in our project, we encountered a build issue indicating that a strong name is required.  Below is the mentioned error occurred while building the solution.

**error MC1000: Unknown build error, 'Could not load file or assembly 'Scintilla.NET, Version=5.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A Strongly-named assembly is required. (Exception from HRESULT: 0x80131044)**
       
**Describe the solution you'd like**
Request to include the strong naming for the assemblies used while referring to the nuget package.

**Describe alternatives you've considered**

**Additional context**

**Comment by desjarlais** [comment]
There is an ongoing discussion about this already:

https://github.com/desjarlais/Scintilla.NET/discussions/100

I think the workaround of forking the repo and making that a signed version would be a better idea than trying to incorporate it into this one...but I am open to other ideas.

**Comment by ahmetsait** [comment]
@desjarlais I don't see why signing this lib is such a big deal?

**Comment by desjarlais** [comment]
I haven't researched what it would take to add it to the project so I'll take a look at what that entails.  It would be a nice to have, I just haven't looked into the possible issues it could cause yet.

**Comment by thehill383** [comment]
came to reserach the exact same issue and found its just been resolved😀
