### ISSUE TITLE
Requesting to include Digital Signature(SHA 256) for the assembly

### ISSUE THREAD

**Issue by KalyaniURS** [desjarlais/Scintilla.NET#143]
**Is your feature request related to a problem? Please describe.**
After referencing the Scintilla.NET NuGet package (v5.6.2) in our project, we encountered a build issue indicating that an assembly should be digitally signed.

**Describe the solution you'd like**
Request to include the digital signature for the assemblies used while referring to the Nuget package.

**Describe alternatives you've considered**

**Additional context**

**Comment by desjarlais** [comment]
My initial thought is to reject this feature request.  I don't have a digital signature, nor do I want to purchase one to get this digitally signed.  If someone wants to fork the repo and take on the digital signature piece for those scenarios that need it, that is fine by me.  

I'm open to other ideas, but that is my initial thoughts.

**Comment by ahmetsait** [comment]
@KalyaniURS You can [digitally sign](https://learn.microsoft.com/en-us/windows/win32/seccrypto/signtool) `Scintilla5.NET.dll` yourself with the same certificate you use to sign binaries that reference it. There is no need to build it from source.

**Comment by KalyaniURS** [comment]
[like]  Upadhyayula Rama Surya Kalyani reacted to your message:
________________________________
