### ISSUE TITLE
Scintilla.dll v. 5.5.2 flagged by VirusTotal

### ISSUE THREAD

**Issue by otykier** [desjarlais/Scintilla.NET#144]
The [/runtimes/win-x64/native/Scintilla.dll](https://github.com/desjarlais/Scintilla.NET/blob/master/Scintilla.NET/runtimes/win-x64/native/Scintilla.dll) file (v. 5.5.2), is flagged by VirusTotal:

https://www.virustotal.com/gui/file/63cccc552650b2532d981ff4e45715c35c1a4f0c6cc6736575e36c634278bed5?nocache=1

It is most likely a false positive, but I thought I'd post this here for awareness.

I've sent a request to the Jiangmin Antivirus team, to perform a closer investigation. Hopefully they will be able to confirm whether this is indeed a false positive or not.

**Comment by desjarlais** [comment]
Thank you for the report, let me know what you find out from Jiangmin.
