### ISSUE TITLE
Ctrl+S adds character DC3 to the text box

### ISSUE THREAD

**Issue by LovelyA72** [desjarlais/Scintilla.NET#146]
**Describe the bug**
When pressing Ctrl+S the control adds DC3 to the text. `e.SupressKeyPress = true` does not work

**To Reproduce**
Press Ctrl+S

**Expected behavior**
Nothing happens after suppressing it from the event

**Screenshots**

![image](https://github.com/user-attachments/assets/dd85b340-2568-4904-bea9-95938deb5e2b)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by desjarlais** [comment]
This does repro, thank you for submitting the issue.  It looks like a CR (Carriage Return) is getting added with that keyboard combination, I'll see what I can find out.

**Comment by desjarlais** [comment]
This looks like something that has been an issue for a long time, not sure it has ever been root caused yet, just workarounds like using the following scintilla event:

private void scintilla1_InsertCheck(object sender, ScintillaNET.InsertCheckEventArgs e)
{
    if (e.Text.Length == 1 && char.IsControl(e.Text[0]))
        e.Text = string.Empty;
}

**Comment by desjarlais** [comment]
@LovelyA72 as a workaround, does the above suggestion work?

**Comment by LovelyA72** [comment]
It worked perfectly! Thank you!
