### ISSUE TITLE
Appearance bug in designer 

### ISSUE THREAD

**Issue by VPKSoft** [desjarlais/Scintilla.NET#74]
@lgaudouen wrote:
> Appearance in design mode related to the CaretLineVisible, CaretLineVisibleAlways, CaretLineBackColor and CaretLineBackColorAlpha properties. When inserting a Scintilla.NET control, the name of the control appears clearly and the values of the CaretLineVisible, CaretLineVisibleAlways properties are set to False by default. If you close the form designer and reopen it, the CaretLineVisible property automatically changes to True.

**Comment by desjarlais** [comment]
This appears to be fixed issue #68 but if that is not correct, let me know.  I'll re-open if this is still not fixed, but if the ClickOnce part of the problem is still a question, create a new issue.
