### ISSUE TITLE
Undo and Redo

### ISSUE THREAD

**Issue by raineym** [desjarlais/Scintilla.NET#83]
I'm trying to implement an undo/redo for Scintilla.NET. I have implemented the undo ... but for the life of me I cannot implement the redo.

Scintilla.NET has a built-in undo, but its Redo() does not work and CanRedo is read-only and set to false when I test for it.

Anyone have any ideas on how to implement/activate the redo?

(Yes, I have done a Google search and here for this issue and found nothing.)

**Comment by lgaudouen** [comment]
Having just read your report of a problem, I just made an extremely simple project to test your problem with version 5.3.2.9 of the package and it seems to work correctly.
Attached is the project:
[Test481.zip](https://github.com/VPKSoft/Scintilla.NET/files/13031249/Test481.zip)

**Comment by desjarlais** [comment]
@lgaudouen @raineym is this issue still reproducing in either 5.3.2.9 or 5.3.3?

**Comment by desjarlais** [comment]
I'm sure this depends on what you are trying to implement and how you are implementing it.  But I don't repro Redo not working.  I did a generic test of adding the following when the control is initialized:

"scintilla1"

Then I added text to the control:

"scintilla1-undotest"

Then I call "scintilla1.Undo();", which does the expected which is changing the control to this:

"scintilla1"

If I then call "scintilla1.Redo();", I see this:

"scintilla1-undotest"

Closing as no repro, but if you can provide a repro of what you are trying to do with Redo() I'll take a look.
