### ISSUE TITLE
New versions of Scintilla.dll ( (5.4.0) and Lexilla.dll (5.2.9)

### ISSUE THREAD

**Issue by lgaudouen** [desjarlais/Scintilla.NET#87]
Coming with Scite v 5.4.0, new versions for scintilla.dll and lexilla.dll ((2023/11/18))
Scintilla: 5.3.9 -> 5.4.0 
Lexilla: 5.2.9 -> 5.2.9

[dlls.zip](https://github.com/VPKSoft/Scintilla.NET/files/13502359/dlls.zip)

(Thanks to Joachim Mairböck)

**Comment by desjarlais** [comment]
@lgaudouen I would be happy to discuss your thoughts on the project, you can email me at brandon.desjarlais@outlook.com.
