### ISSUE TITLE
version 3.3.3.n not found in NuGet Gallery

### ISSUE THREAD

**Issue by lgaudouen** [desjarlais/Scintilla.NET#90]
It seems that the Scintilla.NET v3.3.3.6 package is not released: the latest one available in the NuGet Gallery is v5.3.2.9.
But version 5.3.2.9 in NuGet Gallery doesn't work anymore either.

**Comment by desjarlais** [comment]
I created a new nuget package called "Scintilla5.NET", 

https://www.nuget.org/packages/Scintilla5.NET

**Comment by lgaudouen** [comment]
Thanks a lot.
