### ISSUE TITLE
Lexer.Container is not found

### ISSUE THREAD

**Issue by Pabs84** [desjarlais/Scintilla.NET#92]
is StyleNeeded still supported? how to activate without Lexer.Container ?

will this be supported?

**Comment by desjarlais** [comment]
As far as I can tell, StyleNeeded is supported, what are you trying to accomplish and what is the repro you are attempting?

**Comment by Pabs84** [comment]
AFAIK Lexer.Container doesn't do anything more then calling StyleNeeded callback and no other lexer will call StyleNeeded.

`using ScintillaNET;
using System.Windows;

namespace WpfApp1
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            Text.StyleResetDefault();
            Text.Styles[ScintillaNET.Style.Default].Font = "Consolas";
            Text.Styles[ScintillaNET.Style.Default].Size = 10;
            Text.Styles[ScintillaNET.Style.Default].ForeColor = System.Drawing.Color.Black;
            Text.StyleClearAll();

            Text.Lexer = Lexer.Container;
            Text.Styles[ScintillaNET.Style.Json.Default].ForeColor = System.Drawing.Color.Silver;
            Text.Styles[ScintillaNET.Style.Json.BlockComment].ForeColor = System.Drawing.Color.Green;
            Text.Styles[ScintillaNET.Style.Json.LineComment].ForeColor = System.Drawing.Color.Green;
            Text.Styles[ScintillaNET.Style.Json.Number].ForeColor = System.Drawing.Color.Olive;
            Text.Styles[ScintillaNET.Style.Json.PropertyName].ForeColor = System.Drawing.Color.Blue;
            Text.Styles[ScintillaNET.Style.Json.String].ForeColor = System.Drawing.Color.Brown;
            Text.Styles[ScintillaNET.Style.Json.StringEol].BackColor = System.Drawing.Color.Pink;
            Text.Styles[ScintillaNET.Style.Json.Operator].ForeColor = System.Drawing.Color.Purple;
            Text.Styles[ScintillaNET.Style.Json.Error].ForeColor = System.Drawing.Color.Red;
            Text.Styles[ScintillaNET.Style.Json.Keyword].ForeColor = System.Drawing.Color.Orange;
            Text.SetKeywords(0, "false true null");
            Text.StyleNeeded +=  (s, e) =>
            {
                Scintilla? view = s as Scintilla;
                if (view != null)
                {
                    int startPos = view.GetEndStyled() + 1;
                    int lineStart = view.LineFromPosition(startPos);
                    startPos = view.Lines[lineStart].Position;
                    int endPos = e.Position;

                    view.Lexer = Lexer.Json;
                    view.Colorize(startPos, endPos);

                    view.Lexer = Lexer.Container;
                }
            };


            Text.Text = "[{ \"hello\":\"world\",\"lexer error\":true},{ \":)\":false}]";
        }
    }
}
`

in this example System.InvalidOperationException: 'No lexer name was found with the specified value.'  is thrown when setting Text.Lexer = Lexer.Container;

if you replace the line with
Text.Lexer = Lexer.Json;

it won't call StyleNeeded. and so my conclusion is that without Lexer.Container StyleNeeded is not supported.

**Comment by desjarlais** [comment]
I think you are right, I've been looking at removing those to make it less confusing.  It looks like everything in Lexer.cs is not going to work / is not supported by scintilla.

What is the behavior you are looking to accomplish if it was to get added back in?

**Comment by Pabs84** [comment]
> What is the behavior you are looking to accomplish if it was to get added back in?
when Text.Lexer = Lexer.Container;

Text.StyleNeeded is called; at that point you can dynamically provide the correct lexer or do some other operation, but I do not know all possibilities.

this allows flexibility in lexer selection and allow mixing them.

within the StyleNeeded callback you have to finish by resetting the lexer with Lexer = Lexer.Container; otherwise it won't call again the StyleNeeded callback.

here is an old issue, I tried with older nuget packages and it works:
https://github.com/jacobslusser/ScintillaNET/issues/433

**Comment by desjarlais** [comment]
That makes sense, I'll see how I can add this back in but it could take some time to figure out how to add it back in with the current scintilla libraries.

**Comment by Pabs84** [comment]
> That makes sense, I'll see how I can add this back in but it could take some time to figure out how to add it back in with the current scintilla libraries.

I thought the .net would just forward to scintilla in this case.
would it make sense to tag this as a bug since is not allowing a previously working feature?

**Comment by Pabs84** [comment]
I downloaded the code and made it work, to be honest it is quite trivial to solve, because is not a lexer to be created, but a valid lexer to select. I tried to create a branch and push a possible solution and I get 403, I thought this was public.


from Scintilla Documentation:

> [...] If you choose to use the container to do the styling you can use the [SCI_SETILEXER](https://www.scintilla.org/ScintillaDoc.html#SCI_SETILEXER) command to select NULL, in which case the container is sent a [SCN_STYLENEEDED](https://www.scintilla.org/ScintillaDoc.html#SCN_STYLENEEDED) [notification](https://www.scintilla.org/ScintillaDoc.html#Notifications) each time text needs styling for display. 

I tried it and it works

**Comment by desjarlais** [comment]
@Pabs84 hmm, this should be public, so I'm not sure if a setting changed when this was transferred to me.  Can you send me a screenshot of the 403?

**Comment by Pabs84** [comment]
hi,

ty, I can push now. if you can see the changes here: https://github.com/desjarlais/Scintilla.NET/commit/c868359342493321c067c4c56cba0758db652dfd 

these are the least amount of changes required to get this done. not necessarily the best way. one of the things is that container definition is an empty string, and so we do have a special test against empty string to select the container. Maybe it shouldn't be an empty string in the first place, but maybe there are reasons for it to be like this. You tell me.

**Comment by desjarlais** [comment]
Thank you for the code suggestion, I'll add it in the next release.  I think this is pretty good for now, so I'll take it as is for the first part.

The second part I was already going to remove...actually thinking about removing the lexer.cs file and the Lexer property in scintilla.cs since it is obsolete and I'm not sure there is much use in keeping an enum helper for language name.  Is that something you would find useful or is lexername good for your use cases?

**Comment by desjarlais** [comment]
This should be fixed, at least at a minimum level, I'll keep looking to see if more needs to be done, but this gets StyleNeeded working.

**Comment by Pabs84** [comment]
> Thank you for the code suggestion, I'll add it in the next release. I think this is pretty good for now, so I'll take it as is for the first part.
> 
> The second part I was already going to remove...actually thinking about removing the lexer.cs file and the Lexer property in scintilla.cs since it is obsolete and I'm not sure there is much use in keeping an enum helper for language name. Is that something you would find useful or is lexername good for your use cases?

I personally wouldn't remove it; I believe is too early, it allows legacy to work, does not stop adding lexers, nor any future roadmap feature. the only issue is that people may think the enum is supposedly exhaustive and fully supported in the future, so a good documentation or providing deprecated attribute is necessary.

**Comment by desjarlais** [comment]
What legacy scenarios does it provide?

**Comment by Pabs84** [comment]
> What legacy scenarios does it provide?

the legacy code I talk about is any old code that uses jacobslusser.ScintillaNET, fernandreu.ScintillaNET, old nuget of ScintillaNET, etcc.. that still uses the enum to select lexers. supporting the legacy allows seemless transition to the latest package.

do you support VPKSoft.ScintillaLexers.NET ? it doesn't look fully compatible anyway

**Comment by desjarlais** [comment]
I do support the scintillalexers.net repo.
