### ISSUE TITLE
is json lexer broken ? WPF

### ISSUE THREAD

**Issue by Pabs84** [desjarlais/Scintilla.NET#93]
to verify:
WPF + WindowsFormsHost application
.Net 6
Scintilla.NET v5.3.2.9

`<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        xmlns:ScintillaNET="clr-namespace:ScintillaNET;assembly=Scintilla.NET"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <WindowsFormsHost>
            <ScintillaNET:Scintilla x:Name="Text" Margin="10,31,10,10">
            </ScintillaNET:Scintilla>
        </WindowsFormsHost>
    </Grid>
</Window>
`

`using ScintillaNET;
using System.Windows;

namespace WpfApp1
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            Text.StyleResetDefault();
            Text.Styles[ScintillaNET.Style.Default].Font = "Consolas";
            Text.Styles[ScintillaNET.Style.Default].Size = 10;
            Text.Styles[ScintillaNET.Style.Default].ForeColor = System.Drawing.Color.Black;
            Text.StyleClearAll();

            Text.Lexer = Lexer.Json;
            Text.Styles[ScintillaNET.Style.Json.Default].ForeColor = System.Drawing.Color.Black;
            Text.Styles[ScintillaNET.Style.Json.Number].ForeColor = System.Drawing.Color.Blue;
            Text.Styles[ScintillaNET.Style.Json.String].ForeColor = System.Drawing.Color.Blue;
            Text.Styles[ScintillaNET.Style.Json.StringEol].ForeColor = System.Drawing.Color.Purple;
            Text.Styles[ScintillaNET.Style.Json.PropertyName].ForeColor = System.Drawing.Color.Brown;
            Text.Styles[ScintillaNET.Style.Json.EscapeSequence].ForeColor = System.Drawing.Color.Red;
            Text.Styles[ScintillaNET.Style.Json.LineComment].ForeColor = System.Drawing.Color.DarkGreen;
            Text.Styles[ScintillaNET.Style.Json.BlockComment].ForeColor = System.Drawing.Color.DarkGreen;
            Text.Styles[ScintillaNET.Style.Json.Operator].ForeColor = System.Drawing.Color.LightGray;
            Text.Styles[ScintillaNET.Style.Json.Uri].ForeColor = System.Drawing.Color.LightGray;
            Text.Styles[ScintillaNET.Style.Json.CompactIRI].ForeColor = System.Drawing.Color.LightGray;
            Text.Styles[ScintillaNET.Style.Json.Keyword].ForeColor = System.Drawing.Color.LightGray;
            Text.Styles[ScintillaNET.Style.Json.LdKeyword].ForeColor = System.Drawing.Color.LightGray;
            Text.Styles[ScintillaNET.Style.Json.Error].ForeColor = System.Drawing.Color.Red;

            Text.Text = "[{ \"hello\":\"world\",\"lexer error\":true},{ \":)\":false}]";
        }
    }
}
`

you can see this result:

![Lexer](https://github.com/desjarlais/Scintilla.NET/assets/114940342/10495c3f-2e8c-4271-83e5-f9a48c9aa17e)

the boolean will be parsed as ScintillaNET.Style.Json.Error and will continue until a new line is found :(

**Comment by desjarlais** [comment]
This does repro, I'll take a look and see what I can figure out.

**Comment by desjarlais** [comment]
@Pabs84 I think you need to add keywords for the bool values, something like this:

        scintilla.LexerName = "json";
        scintilla.Styles[Style.Json.Default].ForeColor = Color.Silver;
        scintilla.Styles[Style.Json.BlockComment].ForeColor = Color.Green;
        scintilla.Styles[Style.Json.LineComment].ForeColor = Color.Green;
        scintilla.Styles[Style.Json.Number].ForeColor = Color.Olive;
        scintilla.Styles[Style.Json.PropertyName].ForeColor = Color.Blue;
        scintilla.Styles[Style.Json.String].ForeColor = Color.Brown;
        scintilla.Styles[Style.Json.StringEol].BackColor = Color.Pink;
        scintilla.Styles[Style.Json.Operator].ForeColor = Color.Purple;
        scintilla.Styles[Style.Json.Error].ForeColor = Color.Red;
        scintilla.Styles[Style.Json.Keyword].ForeColor = Color.Orange;
        scintilla.SetKeywords(0, "false true null");
