### ISSUE TITLE
Scintilla control not visible on form designer

### ISSUE THREAD

**Issue by ikorman** [desjarlais/Scintilla.NET#95]
I downloaded latest available source code. Took sample application provided within the repo, add Scintilla.Net control source code as project reference to solution. Program compiles fine and runs, but when in designer mode Scintilla control not visible neither on the form nor control toolbox. Usually I get it through nuget and no issues theres, only in this case when source code is used as part of solution.

Additional issue/request: by default current row is highlighted in black color, meaning you can not see what you type (as font by default is also black), neither caret is visible. Can be confusing for beginners, like it confused also me when switched to this project version - i thought something is wrong with control.

![2023-12-26 18_22_14-Scintilla NET - Microsoft Visual Studio](https://github.com/desjarlais/Scintilla.NET/assets/5569153/39bc4993-5c7f-47ac-8cf1-dc2ab094cc24)
![2023-12-26 18_22_56-ScintillaNET TestApp  © desjarlais 2023](https://github.com/desjarlais/Scintilla.NET/assets/5569153/c19de6f1-ab88-4558-8d87-ab1f10ef7d3c)

Environment is Win11, VS 17.8.3

Thx
Ivan

**Comment by desjarlais** [comment]
The black color is because of this:

https://github.com/desjarlais/Scintilla.NET/blob/4d44c4db34adedc58c62626450cc35ff4e94c52e/Scintilla.NET.TestApp/FormMain.Designer.cs#L136

There are two scintilla controls in the current version of the test app and one of them has the color set to black explicitly.  I'll change the test app back to a white color in the next release.

As for the controls not being visible, I'll take a look and see what I can find.

**Comment by ikorman** [comment]
Regarding black color, I also tried it in another app, by downloading Scintilla nuget package - when control is added to the form, by default color is set to black, so I would say it's not connected to the sample app by it self but rather to property default value

![2023-12-27 10_22_46-Form1](https://github.com/desjarlais/Scintilla.NET/assets/5569153/a5a4f36d-f0ae-4e3c-86d8-d11cfd677406)

**Comment by desjarlais** [comment]
Yes, that is a different scenario with the same symptom of the test app.  I'll create a new Issue for the black color being there by default when you add the control.

**Comment by desjarlais** [comment]
@ikorman the CaretLineBackColor issue will be resolved in the next update (5.3.3.14), I'm still looking into the visibility issue for the test app.
