### ISSUE TITLE
New versions of Scintilla.dll (5.4.1) and Lexilla.dll (5.3.0)

### ISSUE THREAD

**Issue by lgaudouen** [desjarlais/Scintilla.NET#97]
Coming with Scite v 5.4.1, new versions for scintilla.dll and lexilla.dll (2023/12/26)
- **Scintilla**:&nbsp;&nbsp; *5.4.0* &#10230;  **<ins>5.4.1</ins>**
- **Lexilla**:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *5.2.9* &#10230; **<ins>5.3.0</ins>**

[dlls.zip](https://github.com/desjarlais/Scintilla.NET/files/13784684/dlls.zip)

**Comment by desjarlais** [comment]
these should be updated in 5.3.3.12
